AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Module 3 start state

Resources:
  users:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./users/template.yaml
  orders:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./orders/template.yaml
      Parameters:
        UserPool: !GetAtt users.Outputs.UserPool

Outputs:
  CognitoLoginURL:
    Description: Cognito Login Page
    Value: !GetAtt users.Outputs.CognitoLoginURL

  UserNestedStack:
    Description: Nested stack name for users
    Value: !GetAtt users.Outputs.StackName

  OrderNestedStack:
    Description: Nested stack name for orders
    Value: !GetAtt orders.Outputs.StackName
