openapi: "3.0.1"
info:
  title: "API Gateway HTTP API to EventBridge"
paths:
  /:
    post:
      responses:
        default:
          description: "EventBridge response"
      x-amazon-apigateway-integration:
        integrationSubtype: "EventBridge-PutEvents"  # 此 Endpoint 後端會去觸發 EventBridge
        credentials:
          Fn::GetAtt: [MyHttpApiRole, Arn]
        requestParameters:
          Detail: "$request.body.Detail"
          DetailType: MyDetailType
          Source: WebApp
        payloadFormatVersion: "1.0"
        type: "aws_proxy"
        connectionType: "INTERNET"