AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Gateway HTTP API to EventBridge (uksb-1tthgi812)
  (tag:apigw-http-api-eventbridge)

Resources:

  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefinitionBody:
        # OpenAPI, (也可用 DefinitionUri)
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: openapi/apigw-http-api-eventbridge_api.yaml

  # EventBridge 調用 LambdaFn
  MyTriggeredLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/apigw-http-api-eventbridge_api/
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Events:
        EventBridgeTrigger:
          Type: CloudWatchEvent
          Properties:
            # EventBusName: default
            Pattern:
              source:
                - WebApp # 任何發送到 default Bridge 的 Events, 凡事符合了 {"source": "WebApp"} 都會調用 Function

Outputs:
  ApiEndpoint:
    Description: HTTP API endpoint URL
    Value: !Sub https://${MyHttpApi}.execute-api.${AWS::Region}.amazonaws.com