AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless patterns - Amazon API Gateway REST API with API Key (uksb-1tthgi812) (tag:apigw-api-key)

Globals:
  Function:
    Runtime: nodejs22.x
    CodeUri: src/apigw-rest-api-usage-plan/

Resources:

  AppApi:
    Type: AWS::ApiGateway::RestApi  # (非 SAM) RestApi
    Properties:
      Name: apigw-api-key
      Description: API key REST API demo

  # GET Method
  RootMethodGet:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref AppApi
      ResourceId: !GetAtt AppApi.RootResourceId
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: True
      Integration:  # ApiGw 的 backend
        Type: AWS_PROXY  # AWS | AWS_PROXY | HTTP | HTTP_PROXY | MOCK . 目前情境為 Lambda proxy integration
        IntegrationHttpMethod: POST
        Uri: !Join ['', ['arn:aws:apigateway:', !Ref AWS::Region, ':lambda:path/2015-03-31/functions/', !GetAtt AppFunction.Arn, '/invocations']]

  # Dummy function
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/apigw-rest-api-usage-plan/
      Handler: app.handler

  # ApiGw 調用 LambdaFn 的 Role
  AppFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AppFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AppApi}/*/GET/

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties: 
      ApiStages: 
        - ApiId: !Ref AppApi
          Stage: !Ref Stage

  ApiKey:  # 建立一把 ApiKey
    Type: AWS::ApiGateway::ApiKey
    Properties: 
      Enabled: True

  UsagePlanKey:
    # ApiKey 必須關聯到 Usage Plan
    # ApiKey 一定要關聯到 Api 及 Stage, 至於底下的 path 及 method 則可選擇性指定
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey  
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
    - RootMethodGet
    Properties:
      RestApiId: !Ref AppApi

  Stage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: Prod
      RestApiId: !Ref AppApi
      DeploymentId: !Ref Deployment

Outputs:
  AppApiEndpoint:
    Description: API Endpoint
    Value: !Sub "https://${AppApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  ApiKeyId:
    Description: API Key
    Value: !Ref ApiKey
  UsagePlanId:
    Description: Usage Plan Key
    Value: !Ref UsagePlan